[package]
name = "actor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = { workspace = true }

crossbeam = { workspace = true }
futures = { workspace = true, features = ["async-await"]}
serde = { workspace = true, features = ["derive"] }
thiserror ={ workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "sync", "time"] }
tokio-util = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
criterion = { workspace = true, features = ["html_reports"] }
serial_test = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"]}
tracing-test = { workspace = true }

[[bench]]
name = "actor_benchmarks"
harness = false
