[package]
name = "store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
actor = { path = "../actor" }
async-trait = { workspace = true }
fjall = { version= "3.1.0", optional = true }
serde = { workspace = true, default-features = false, features = ["derive"] }
serde_bare = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "sync", "time"] }
tokio-util = { workspace = true }

[features]
default = ["fjall"]
memory = []