//

use crate::{PersistentActor, stores::{IteratorOptions, Store}};
use actor::{Actor, DummyEvent, Error as ActorError, Event, Message, Response};
use serde_bare::{to_vec, from_slice};
use async_trait::async_trait;
use tracing::{error, debug};

/// A journal that stores events for an event-sourced actor. The journal is responsible for
/// persisting events and providing them to the actor when it needs to replay its state. The 
/// journal also keeps track of the latest sequence number for the events, allowing actors 
/// to know up to which point they have replayed.
pub struct Journal<S: Store> {
    /// The underlying store used for persisting events.
    store: S,
    /// The latest sequence number of the events.
    latest_sequence: u64,    
}

impl<S: Store> Journal<S> {
    /// Creates a new journal with the given store.
    /// 
    /// # Arguments
    /// 
    /// * `name` - A string slice that holds the name of the journal.
    /// * `store` - An instance of a store that implements the `Store` trait
    /// 
    /// # Returns
    /// 
    /// A new instance of `Journal` initialized with the provided name and store, and the latest
    /// sequence set to 0.
    /// 
    pub fn new(store: S) -> Self {
        Self {
            store,
            latest_sequence: 0,
        }
    }

    /// Retrieves the latest sequence number of the data stored in the journal. This method allows
    /// actors to know up to which point they have replayed.
    pub fn latest_sequence(&self) -> u64 {
        self.latest_sequence
    }

    /// Persists data in the journal by storing it in the underlying store and updating the latest
    /// sequence number. This method is used to save events generated by actors, ensuring that 
    /// they are reliably stored and can be replayed later.
    /// 
    /// # Arguments
    /// 
    /// * `data` - The event data to be persisted in the journal.
    /// 
    /// # Returns
    /// 
    /// A `Result` indicating whether the data was successfully persisted or if an error occurred.
    /// On success, it returns `Ok(())`. On failure, it returns an `ActorError` with a message 
    /// describing the error.
    pub fn put<A: PersistentActor>(&mut self, data: A::Event) -> Result<(), ActorError> {
        self.latest_sequence += 1;
        let binary = to_vec(&data)
            .map_err(|e| ActorError::Serialization(
                format!("Failed to serialize event: {}", e)
            ))?;
        Ok(self.store.put(self.latest_sequence, &binary)
            .map_err(|e| ActorError::Store(
                format!("Failed to store event: {}", e))
            )?)
    }

    /// Retrieves data from the journal for a specific sequence number. This method allows actors
    /// to access previously persisted events.
    /// 
    /// # Arguments
    /// 
    /// * `sequence` - The sequence number of the event to retrieve.
    /// 
    /// # Returns
    /// 
    /// A `Result` containing the data for the specified sequence number, or an `ActorError` if
    /// the retrieval fails. On success, it returns `Ok(Vec<u8>)` with the data. On failure, it 
    /// returns an `ActorError` with a message describing the error.
    /// 
    pub fn get<A: PersistentActor>(&self, sequence: u64) -> Result<A::Event, ActorError> {
        let data = self.store.get(sequence)
            .map_err(|e| ActorError::Store(
                format!("Failed to retrieve event: {}", e))
            )?;
        Ok(from_slice::<A::Event>(&data)
            .map_err(|e| ActorError::Deserialization(
                format!("Failed to deserialize event: {}", e)
            ))?)
    }

    /// Retrieves the latest event from the journal. This method allows actors to access the most
    /// recently persisted event.
    /// 
    /// # Returns
    /// 
    /// A `Result` containing the latest event, or an `ActorError` if the retrieval fails. On
    /// success, it returns `Ok(Some((u64, Vec<u8>)))` with the sequence number and data of the
    /// latest event. If no events are present, it returns `Ok(None)`. On failure, it returns an
    /// `ActorError` with a message describing the error.
    pub fn last<A: PersistentActor>(&self) -> Option<(u64, A::Event)> {
        self.get(self.latest_sequence).ok()
            .map(|event| (self.latest_sequence, event))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::stores::{DbManager, memory::MemoryDbManager};
    #[cfg(feature = "fjall")]
    use crate::stores::fjall::FjallDbManager;
    use actor::{Config, System};
    use tokio_util::sync::CancellationToken;

    #[test]
    #[serial_test::serial]
    fn test_journal_memory() {
        let manager = MemoryDbManager::default();
        let store = manager.create_store("test_journal", "event").unwrap();
        let journal = Journal::new(store);


    }

    #[test]
    #[cfg(feature = "fjall")]
    #[serial_test::serial]
    fn test_journal_fjall() {
        let manager = FjallDbManager::default();
        let store = manager.create_store("test_journal_fjall", "event").unwrap();
        let journal = Journal::new(store);

    }
}
