//

use crate::stores::{IteratorOptions, Store};
#[cfg(feature = "fjall")]
use crate::stores::fjall::FjallStore;
#[cfg(feature = "memory")]
use crate::stores::memory::MemoryStore;

use actor::{Actor, ActorContext, ActorPath, DummyEvent, Error as ActorError, Message, Response};
use async_trait::async_trait;
use tracing::error;

#[cfg(feature = "memory")]
pub type Journal = BaseJournal<MemoryStore>;

#[cfg(feature = "fjall")]
pub type Journal = BaseJournal<FjallStore>;

/// A journal that stores events for an event-sourced actor. The journal is responsible for
/// persisting events and providing them to the actor when it needs to replay its state. The 
/// journal also keeps track of the latest sequence number for the events, allowing actors 
/// to know up to which point they have replayed.
///
pub struct BaseJournal<S: Store> {
    /// The underlying store used for persisting events.
    store: S,
    /// The latest sequence number of the events.
    latest_sequence: u64,    
}

impl<S: Store> BaseJournal<S> {
    /// Creates a new journal with the given store.
    /// 
    /// # Arguments
    /// 
    /// * `store` - An instance of a store that implements the `Store` trait
    /// 
    /// # Returns
    /// 
    /// A new instance of `BaseJournal` initialized with the provided store, and the latest
    /// sequence set to the latest sequence from the store.
    /// 
    pub fn new(store: S) -> Self {
        let mut latest_sequence = 0_u64;
        if let Some((seq, _)) = store.last() {
            latest_sequence = seq;
        }
        Self {
            store,
            latest_sequence,
        }
    }

    /// Retrieves the latest sequence number of the data stored in the journal. This method allows
    /// actors to know up to which point they have replayed.
    pub fn latest_sequence(&self) -> u64 {
        self.latest_sequence
    }

    /// Persists data in the journal by storing it in the underlying store and updating the latest
    /// sequence number. This method is used to save events generated by actors, ensuring that 
    /// they are reliably stored and can be replayed later.
    /// 
    /// # Arguments
    /// 
    /// * `data` - The event data to be persisted in the journal.
    /// 
    /// # Returns
    /// 
    /// A `Result` indicating whether the data was successfully persisted or if an error occurred.
    /// On success, it returns `Ok(())`. On failure, it returns an `ActorError` with a message 
    /// describing the error.
    pub fn put(&mut self, data: &[u8]) -> Result<(), ActorError> {
        self.latest_sequence += 1;
        self.store.put(self.latest_sequence, data)
            .map_err(|e| {
                error!("Failed to store event in journal: {}", e);
                ActorError::Store(
                    format!("Failed to store event: {}", e))
            })
    }

    /// Retrieves data from the journal for a specific sequence number. This method allows actors
    /// to access previously persisted events.
    /// 
    /// # Arguments
    /// 
    /// * `sequence` - The sequence number of the event to retrieve.
    /// 
    /// # Returns
    /// 
    /// A `Result` containing the data for the specified sequence number, or an `ActorError` if
    /// the retrieval fails. On success, it returns `Ok(Vec<u8>)` with the data. On failure, it 
    /// returns an `ActorError` with a message describing the error.
    /// 
    pub fn get(&self, sequence: u64) -> Result<Vec<u8>, ActorError> {
        self.store.get(sequence)
            .map_err(|e| {
                error!("Failed to retrieve event from journal: {}", e);
                ActorError::Store(
                    format!("Failed to retrieve event: {}", e))
            })
    }

    /// Retrieves the latest event from the journal. This method allows actors to access the most
    /// recently persisted event.
    /// 
    /// # Returns
    /// 
    /// A `Result` containing the latest event, or an `ActorError` if the retrieval fails. On
    /// success, it returns `Ok(Some((u64, Vec<u8>)))` with the sequence number and data of the
    /// latest event. If no events are present, it returns `Ok(None)`. On failure, it returns an
    /// `ActorError` with a message describing the error.
    pub fn last(&self) -> Option<(u64, Vec<u8>)> {
        self.get(self.latest_sequence).ok()
            .map(|event| (self.latest_sequence, event))
    }

    /// Retrieves a range of events from the journal based on the provided sequence numbers. 
    /// This method allows actors to access a subset of previously persisted events.
    /// 
    /// # Arguments
    /// 
    /// * `from` - The starting sequence number of the range.
    /// * `to` - The optional ending sequence number of the range. If `None`, it defaults to the latest sequence number.
    /// 
    /// # Returns
    /// 
    /// A `Result` containing a vector of events within the specified range, or an `ActorError` if the retrieval fails.
    /// On success, it returns `Ok(Vec<(u64, Vec<u8>)>)` with the sequence numbers and data of the events.
    /// On failure, it returns an `ActorError` with a message describing the error.
    ///
    pub fn range(&self, from: u64, to: Option<u64>) -> Vec<(u64, Vec<u8>)> {
        let options = IteratorOptions::Range { from, to };
        self.store.iter(options).collect::<Vec<(u64, Vec<u8>)>>()
    }

    /// Flushes the journal's store to ensure that all pending writes are persisted. This 
    /// method is typically called during shutdown to ensure that all events are saved properly.
    /// 
    /// # Returns
    /// 
    /// * `Result<(), ActorError>` - Ok if the flush was successful, or an error if there was a 
    ///   problem during flushing.
    ///
    fn flush(&mut self) -> Result<(), ActorError> {
        self.store.flush()
            .map_err(|e| {
                error!("Failed to flush store: {}", e);
                ActorError::Store(format!("Failed to flush store: {}", e))
            })
    }

}

/// Messages that can be sent to the journal actor to perform various operations such as putting
/// events, retrieving events, and flushing the journal. These messages define the interface for
/// interacting with the journal actor, allowing other actors to persist and access events in a
/// standardized way.
#[derive(Clone)]
pub enum JournalMessage {
    /// Message to persist an event in the journal. The event data is provided as a vector of 
    /// bytes.
    Put(Vec<u8>),
    /// Message to retrieve an event from the journal by its sequence number.
    Get(u64),
    /// Message to retrieve the latest event from the journal.
    Last,
    /// Message to retrieve the latest sequence number from the journal.
    LastSequence,
    /// Message to retrieve a range of events from the journal. The `from` parameter specifies 
    /// the starting sequence number, and the optional `to` parameter specifies the ending 
    /// sequence number. If `to` is `None`, it defaults to the latest sequence number.
    Range(u64, Option<u64>),
    /// Message to flush the journal's store, ensuring that all pending writes are persisted.
    Flush,
}
    
impl Message for JournalMessage {}

/// Responses that the journal actor can return in response to messages. These responses provide
/// the results of operations performed by the journal actor, such as retrieving events or
/// confirming that an event was persisted successfully. The responses are designed to be flexible
/// and can represent various outcomes, including successful retrieval of events, not found cases,
/// and errors.
pub enum JournalResponse {
    /// Response indicating that an event was successfully retrieved from the journal, containing 
    /// the event data.
    Event(Vec<u8>),
    /// Response indicating that a range of events was successfully retrieved from the journal, 
    /// containing the sequence numbers and event data.
    Events(Vec<(u64, Vec<u8>)>),
    /// Response indicating that the latest event was successfully retrieved from the journal, 
    /// containing the sequence number and event data.
    Last(u64, Vec<u8>),
    /// Response indicating that the latest sequence number was successfully retrieved from the 
    /// journal.
    LastSequence(u64),
    /// Response indicating that the requested event was not found in the journal.
    NotFound,
    /// Response indicating that the operation was successful but there is no specific data to 
    /// return.
    None,
}

impl Response for JournalResponse {}

/// Implementation of the `Actor` trait for the `BaseJournal` struct. This implementation defines
/// how the journal actor handles messages and produces responses.
#[async_trait]
impl<S: Store> Actor for BaseJournal<S> {
    type Message = JournalMessage;
    type Response = JournalResponse;
    type Event = DummyEvent;

    async fn handle(
        &mut self, 
        _ctx: &mut ActorContext<Self>,
        _sender: &ActorPath,
        msg: Self::Message,
    ) -> Result<Self::Response, ActorError> {
        match msg {
            JournalMessage::Put(event) => {
                match self.put(&event) {
                    Ok(_) => Ok(JournalResponse::LastSequence(self.latest_sequence)),
                    Err(e) => Err(ActorError::Store(
                        format!("Failed to put event in journal: {}", e)
                    )),
                }
            },
            JournalMessage::Get(sequence) => {
                match self.get(sequence) {
                    Ok(event) => Ok(JournalResponse::Event(event)),
                    Err(e) => Err(ActorError::Store(
                        format!("Failed to get event from journal: {}", e)
                    )),
                }
            },
            JournalMessage::Last => {
                match self.last() {
                    Some((seq, event)) => Ok(JournalResponse::Last(seq, event)),
                    None => Ok(JournalResponse::NotFound),
                }
            },
            JournalMessage::LastSequence => {
                let seq = self.latest_sequence();
                Ok(JournalResponse::LastSequence(seq))
            },
            JournalMessage::Range(from, to) => {
                let events = self.range(from, to);
                Ok(JournalResponse::Events(events))
            },
            JournalMessage::Flush => {
                match self.flush() {
                    Ok(_) => Ok(JournalResponse::None),
                    Err(e) => Err(ActorError::Store(
                        format!("Failed to flush journal: {}", e)
                    )),
                }
            },
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::stores::{StoreManager, DbManager};
    use actor::{Config, System};
    use tokio_util::sync::CancellationToken;

    #[tokio::test]
    #[serial_test::serial]
    async fn test_journal() {
        let token = CancellationToken::new();
        let mut system = System::new(Config::default(), token);
        let manager = StoreManager::default();
        system.add_helper("storage", manager.clone()).await;
        let store = manager.create_store("test_journal", "event").unwrap();
        let journal = Journal::new(store);
        let journal = system.create_actor(journal, "journal").await.unwrap();
        for i in 1..=5 {
            let event = format!("test event {}", i).into_bytes();
            let response = journal.ask(JournalMessage::Put(event)).await.unwrap();
            match response {
                JournalResponse::LastSequence(seq) => assert_eq!(seq, i),
                _ => panic!("Expected JournalResponse::LastSequence"),
            }
        }
        let event = format!("test event {}", 3).into_bytes();
        let response = journal.ask(JournalMessage::Get(3)).await.unwrap();
        match response {
            JournalResponse::Event(data) => assert_eq!(data, event),
            _ => panic!("Expected JournalResponse::Event"),
        }
        let response = journal.ask(JournalMessage::Last).await.unwrap();
        match response {
            JournalResponse::Last(seq, data) => {
                assert_eq!(seq, 5);
                let expected_event = format!("test event {}", 5).into_bytes();
                assert_eq!(data, expected_event);
            },
            _ => panic!("Expected JournalResponse::Last"),
        }
        let response = journal.ask(JournalMessage::Range(2, Some(4))).await.unwrap();
        match response {
            JournalResponse::Events(events) => {
                assert_eq!(events.len(), 3);
                for (i, (seq, data)) in events.into_iter().enumerate() {
                    assert_eq!(seq, (i as u64) + 2);
                    let expected_event = format!("test event {}", (i as u64) + 2).into_bytes();
                    assert_eq!(data, expected_event);
                }
            },
            _ => panic!("Expected JournalResponse::Events"),
        }

        // Test flushing the journal
        let response = journal.tell(JournalMessage::Flush).await;
        assert!(response.is_ok());
        
        assert!(manager.drop().is_ok());        
    }

}
